### ISSUE TITLE
Path pattern failed in matching on Windows

### ISSUE THREAD

**Issue by noru** [stipsan/bulma-loader#17]
Hi Stian,

This pattern is not working on Windows since it has `C:\\...\\node_modules\\bulma\\bulma.sass` kinda path:

```
var bulmaPattern = /node_modules\/bulma\/.+sass$/;
```

This one works fine although I'm not sure if it is the best:

```
var bulmaPattern = /node_modules(\/|\\)bulma(\/|\\).+sass$/;
```

I can send a PR if it is ok.

Regards and Thanks!
Drew

**Comment by stipsan** [comment]
https://github.com/stipsan/bulma-loader#this-project-is-no-longer-maintained
